[build-system]
requires = ["hatchling==1.18.0"]
build-backend = "hatchling.build"

[project]
name = "pfns"
version = "0.4.2"
authors = [
{name="Samuel Muller"},
{name="Matthias Feurer"},
{name="Noah Hollmann"},
{name="Frank Hutter"},
]

description = "PFNs"
requires-python = ">=3.11"
dependencies=[
        'torch>=2.2',
        'scikit-learn>=0.24.2',
        'pyyaml>=5.4.1',
        'numpy>=1.21.2',
        'pandas>=2.0.0',
        'gpytorch>=1.5.0',
        'openml',
        'configspace>=0.4.21',
        'tqdm>=4.62.1',
        'scipy>=1.10.0',
        'xgboost',
        'catboost',
        'matplotlib>=3.10.1',
        'seaborn>=0.13.0',
        'einops>=0.8.1',
        'tabicl',
        'tabpfn',
        'flash-linear-attention==0.4.2',
        'pytest>=5.4.3',
        'wandb>=0.16.0',
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[tool.hatch.build]
exclude = [
  "*.gz",
  "*.pt",
  "*.cpkt",
]
